version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "FB-001"
    labels:
      - "npm"
      - "dependencies"  
    reviewers:
      - "Algoritm211"